---
- hosts: test_server
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: adding multiverse repo
      shell: add-apt-repository multiverse
    - name: apt upgrade
      apt:
        update_cache: yes
        upgrade: full
    - name: Adding icingakey
      apt_key:
        url: https://packages.icinga.com/icinga.key
        id: F51A91A5EE001AA5D77D53C4C6E319C334410682
    - name: Adding icinga repo
      template:
        src: icinga.j2
        dest: /etc/apt/sources.list.d/icinga.list
        backup: yes
    - name: Adding certbot repo
      apt_repository:
        repo: 'ppa:certbot/certbot'
    - name: Updating cache
      apt:
        update_cache: yes
    - name: Installing basic packages
      apt:
        name:
          - vim
          - screen
          - python-certbot-apache
          - rdiff-backup
          - python3-pip
          - python-pip
          - wget
          - rsync
          - icinga2
          - icingaweb2
          - icinga2-ido-mysql
          - icingacli
          - monitoring-plugins
          - apache2
          - php
          - libapache2-mod-php
          - php-mysql
          - php-ldap
          - vim-icinga2
          - mysql-server
          - vim-addon-manager
        update_cache: yes
        state: latest
    - name: enable ssl module
      apache2_module:
        state: present
        name: ssl
    - name: start and enable icinga
      service:
        name: icinga2
        enabled: yes
        state: started
    - name: start and enable apache
      service:
        name: apache2
        enabled: yes
        state: restarted
    - name: Replacing service file
      template:
        src: services.j2
        dest: /etc/icinga2/conf.d/services.conf
        backup: yes


