---
# centos 7 only, however feel free to change the
- hosts: rhel
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Adding epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Adding icinga repo
      yum:
        name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
        state: present
    - name: install icinga key
      rpm_key:
        state: present
        key: https://packages.icinga.com/icinga.key
    - name: Installing basic packages
      yum:
        name:
          - vim
          - vim-enhanced
          - screen
          - rdiff-backup
          - wget
          - rsync
          - python34
          - python34-pip
          - python2-pip
          - icinga2
          - nagios-plugins-all
          - vim-icinga2
          - icinga2-selinux
        update_cache: yes
        state: latest
    - name: include vars
      include_vars:
        file: "{{ ansible_hostname }}.yml"
        name: host
    - name: creating cert_folder
      file:
        path: /var/lib/icinga2/certs
        state: directory
        owner: icinga
        group: icinga
        mode: 0755
    - name: creating cert_key
      shell:
        icinga2 pki new-cert --cn short_name --key /var/lib/icinga2/certs/"{{host.get('short_name')}}".key --cert /var/lib/icinga2/certs/"{{host.get('short_name')}}".crt
    - name: getting certificate of master
      shell:
        icinga2 pki save-cert --key /var/lib/icinga2/certs/"{{host.get('short_name')}}".key --cert /var/lib/icinga2/certs/"{{host.get('short_name')}}".crt --trustedcert /var/lib/icinga2/certs/trusted-parent.crt --host "{{host.get('master_server')}}"
    - name: joining node to master
      shell:
        icinga2 node setup --ticket "{{host.get('request_ticket')}}" --cn "{{host.get('short_name')}}" --endpoint "{{host.get('master_shortname')}}","{{host.get('master_server')}}",5665 --zone "{{host.get('short_name')}}" --parent_zone master --parent_host "{{host.get('master_server')}}" --trustedcert /var/lib/icinga2/certs/trusted-parent.crt --accept-commands --accept-config --disable-confd
    - name: start and enable icinga
      service: icinga2
      enabled: yes
      state: started
