---
- hosts: rhel
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Adding epel repo
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Adding icinga repo
      yum:
        name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
        state: present
    - name: install icinga key
      rpm_key:
        state: present
        key: https://packages.icinga.com/icinga.key
    - name: installing yum utils
      yum:
        name:
          - yum-utils
        state: present
    - name: Installing basic packages
      yum:
        name:
          - vim
          - vim-enhanced
          - screen
          - python-certbot-apache
          - rdiff-backup
          - python34-pip
          - python2-pip
          - python2-certbot-apache
          - wget
          - rsync
          - icinga2
          - icingaweb2
          - icinga2-ido-mysql
          - icingacli
          - monitoring-plugins
          - httpd
          - httpd-devel
          - php
          - php-mysql
          - php-ldap
          - vim-icinga2
        update_cache: yes
        state: latest
    - name: Replacing service file
      template:
        src: services.j2
        dest: /etc/icinga2/conf.d/services.conf
        backup: yes


